build wasm go plugin test

diff --git a/.github/workflows/build-and-push-wasm-go-plugin.yaml b/.github/workflows/build-and-push-wasm-go-plugin.yaml
--- a/.github/workflows/build-and-push-wasm-go-plugin.yaml
+++ b/.github/workflows/build-and-push-wasm-go-plugin.yaml
@@ -47,11 +47,26 @@ jobs:
           fi
           
           for plugin in ${PLUGIN_DIRS[@]}; do
-            echo "Building and pushing wasm go plugin: ${plugin}"
-            IMAGE="${{ env.IMAGE_REGISTRY_SERVICE }}/${{ env.IMAGE_REPOSITORY }}/wasm-go-${plugin}:${PLUGIN_VERSION}"
-            PLUGIN_DIR="./extensions/${plugin}"
+            max_retries=3
+            retries=0
+            while [ ${retries} -lt ${MAX_RETRIES} ]; do       
+              echo "Build and push wasm go plugin: ${plugin}"
+              IMAGE="${{ env.IMAGE_REGISTRY_SERVICE }}/${{ env.IMAGE_REPOSITORY }}/wasm-go-${plugin}:${PLUGIN_VERSION}"
+              PLUGIN_DIR="./extensions/${plugin}"      
+              GOPROXY="https://proxy.golang.org,direct" PLUGIN_NAME="${plugin}" make build
+              
+              if [ $? -eq 0 ]; then
+                tar czvf ${PLUGIN_DIR}/plugin.tar.gz ${PLUGIN_DIR}/plugin.wasm
+                oras push $IMAGE ${PLUGIN_DIR}/plugin.tar.gz:application/vnd.oci.image.layer.v1.tar+gzip
+                break
+              else
+                retries=(( retries++ ))
+                echo "Build failed. Retrying (${retries}/${max_retries})..."
+              fi
+            done
           
-            GOPROXY="https://proxy.golang.org,direct" PLUGIN_NAME="${plugin}" make build
-            tar czvf ${PLUGIN_DIR}/plugin.tar.gz ${PLUGIN_DIR}/plugin.wasm
-            oras push $IMAGE ${PLUGIN_DIR}/plugin.tar.gz:application/vnd.oci.image.layer.v1.tar+gzip
+            if [ ${retries} -eq ${max_retries} ]; then
+              echo "Build failed after ${max_retries} retries."
+              exit 1
+            fi
           done
